work_dir: '001_resnet50_BCE_5class_fold0'

data:
  name: 'StealDataset'
  train_dir: '../Datasets/caliche/severstal-steel-defect-detection/train_images'
  test_dir: '../Datasets/caliche/severstal-steel-defect-detection/test_images'
  sample_submission_path: '../Datasets/caliche/severstal-steel-defect-detection/sample_submission.csv'
  train_df_path: '../Datasets/caliche/severstal-steel-defect-detection/train.csv'
  params:
    idx_fold: 0
    num_folds: 5
  num_classes: 5

model:
  arch: 'Classification'
  encoder: 'resnet50'
  pretrained: 'imagenet'

train:
  batch_size: 8
  num_epochs: 40

test:
  batch_size: 32
  best_threshold: 0.5
  min_size: [500, 500, 1000, 2000]

loss:
  name: "BCE"
  params:
    focal_gamma: 0

optimizer:
  name: 'RAdam'
  params:
    decoder_lr: 0.001
    encoder_lr: 0.0001

scheduler:
  name: 'plateau'

num_workers: 8
device: 'cuda'
